name: Build iOS App

on:
  push:
    branches:
     - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Precache Flutter iOS artifacts
        run: |
          flutter precache --ios

      - name: Get Flutter dependencies
        run: |
          flutter pub get

      - name: Update iOS Deployment Target to 16.0
        run: |
          cd ios
          sed -i '' 's/platform :ios, '\''[0-9]*'\''/platform :ios, '\''16.0'\''/g' Podfile

      - name: Build iOS app
        run: |
          flutter build ios --release --no-codesign

      # Upload the iOS build (IPA file) as an artifact
      - name: Upload IPA file
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/ipa/*.ipa
