name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1
          export PATH="$PATH:`pwd`/flutter/bin"

      - name: Flutter clean
        run: flutter clean

      - name: Flutter packages get
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/ipa
